OBT_SAMPLE = """
SELECT *
FROM OBT
LIMIT 5000
"""

BOOKINGS_BY_CITY = """
SELECT
    CITY,
    COUNT(DISTINCT BOOKING_ID) AS total_bookings,
    AVG(TOTAL_CHARGE) AS avg_charge
FROM OBT
WHERE CITY IS NOT NULL
GROUP BY CITY
ORDER BY total_bookings DESC
LIMIT 15
"""

PRICE_BY_ROOM_TYPE = """
SELECT
    ROOM_TYPE,
    AVG(PRICE_PER_NIGHT) AS avg_price,
    MIN(PRICE_PER_NIGHT) AS min_price,
    MAX(PRICE_PER_NIGHT) AS max_price,
    COUNT(*) AS total_listings
FROM OBT
WHERE ROOM_TYPE IS NOT NULL
GROUP BY ROOM_TYPE
"""

BOOKINGS_OVER_TIME = """
SELECT
    DATE_TRUNC('month', BOOKING_DATE) AS booking_month,
    COUNT(*) AS booking_count,
    SUM(TOTAL_CHARGE) AS total_revenue
FROM OBT
WHERE BOOKING_DATE IS NOT NULL
GROUP BY booking_month
ORDER BY booking_month
"""

SUPERHOST_PERFORMANCE = """
SELECT
    IS_SUPERHOST,
    COUNT(DISTINCT HOST_ID) AS host_count,
    AVG(PRICE_PER_NIGHT) AS avg_price,
    AVG(TOTAL_CHARGE) AS avg_booking_value
FROM OBT
WHERE IS_SUPERHOST IS NOT NULL
GROUP BY IS_SUPERHOST
"""

BOOKING_STATUS_BREAKDOWN = """
SELECT
    BOOKING_STATUS,
    COUNT(*) AS count
FROM OBT
WHERE BOOKING_STATUS IS NOT NULL
GROUP BY BOOKING_STATUS
"""

PROPERTY_TYPE_DISTRIBUTION = """
SELECT
    PROPERTY_TYPE,
    COUNT(*) AS listing_count,
    AVG(ACCOMMODATES) AS avg_accommodates
FROM OBT
WHERE PROPERTY_TYPE IS NOT NULL
GROUP BY PROPERTY_TYPE
ORDER BY listing_count DESC
LIMIT 10
"""